### ISSUE TITLE
Не работатет подсветка синткасиса в 1.0.0.3

### ISSUE THREAD

**Issue by andrewzola** [cpr1c/markdowneditor1c#1]
Релиз платформы 8.3.16.1224, 8.3.17.1549, 8.3.18.1289
не работает подсветка синтаксиса 1С

![image](https://user-images.githubusercontent.com/37068126/105007424-08b31a80-5a49-11eb-9ab5-18e946b240bd.png)

**Comment by LevkinSergey** [comment]
Исправлено в 1.0.0.4
