### ISSUE TITLE
Не все объекты включены в подсистему РМ_Markdown

### ISSUE THREAD

**Issue by andrewzola** [cpr1c/markdowneditor1c#3]
Часть объектов не включена в подсистему, это не очень удобно при встраивании и обновлении конфигурации

![image](https://user-images.githubusercontent.com/37068126/105819639-7b804080-5fc9-11eb-871f-d78ca2fd0c3b.png)

**Comment by LevkinSergey** [comment]
Исправлено в версии 1.0.1.0
